name: Build Android APK

on:
  push:
    branches:
      - feature/valify-kyc-integration
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug or release)'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: beneficiary-app-mobile/package-lock.json

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        working-directory: beneficiary-app-mobile
        run: npm ci

      - name: Create .env file
        working-directory: beneficiary-app-mobile
        run: |
          cat > .env << EOF
          # BSP Backend API
          BSP_API_URL=https://dev-bsp.healthflow.eg/api/v1
          BSP_API_KEY=dev_key_placeholder
          
          # HCX Gateway
          HCX_GATEWAY_URL=https://dev-hcx.healthflow.eg
          HCX_PARTICIPANT_CODE=BSP001
          
          # Valify KYC Service
          VALIFY_API_URL=https://valifystage.com
          VALIFY_USERNAME=healthflow__79742_integration_bundle
          VALIFY_PASSWORD=9ud5nKUeC@96W3S7
          VALIFY_CLIENT_ID=lwsx7HOCt5o3bm6QmxBb3F3TExi72drzayCIZOnh
          VALIFY_CLIENT_SECRET=Uv24K9zhKs6kiPpySvE2pnIo2Zzu29Ii8glz2cYMmu2QESJeMw1nWP5g4w2JaceVaCDagsulvmboI490HTAWz9paFXczdjWDYuTGj34d4tjuv9kY5UfTGGbmNMdfQ5bE
          VALIFY_BUNDLE_KEY=b2978014d0b94653be8da42d5d99058b
          
          # App Configuration
          APP_ENV=development
          API_TIMEOUT=30000
          ENABLE_LOGGING=true
          EOF

      - name: Make gradlew executable
        working-directory: beneficiary-app-mobile/android
        run: chmod +x gradlew

      - name: Build Debug APK
        if: github.event.inputs.build_type != 'release'
        working-directory: beneficiary-app-mobile/android
        run: ./gradlew assembleDebug --no-daemon

      - name: Build Release APK
        if: github.event.inputs.build_type == 'release'
        working-directory: beneficiary-app-mobile/android
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload Debug APK
        if: github.event.inputs.build_type != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: beneficiary-app-mobile/android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Upload Release APK
        if: github.event.inputs.build_type == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: beneficiary-app-mobile/android/app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 30

      - name: Get APK Info
        if: success()
        run: |
          echo "✅ APK Build Successful!"
          echo ""
          echo "📦 APK Details:"
          if [ "${{ github.event.inputs.build_type }}" == "release" ]; then
            ls -lh beneficiary-app-mobile/android/app/build/outputs/apk/release/
          else
            ls -lh beneficiary-app-mobile/android/app/build/outputs/apk/debug/
          fi

      - name: Comment PR with APK
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Android APK built successfully!\n\n📦 Download the APK from the [Actions artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'
            })
